// Get all types
GET http://localhost:5000/api/types?page=1&limit=12 HTTP/1.1

###
// Create new type
POST http://localhost:5000/api/types/ HTTP/1.1
Content-Type: application/json

{
    "title": "New type"
}

###
// Update type by ID
PATCH http://localhost:5000/api/types/ HTTP/1.1
Content-Type: application/json

{
    "_id": "66bdf9590fb7e51ea15f2fad",
    "title": "Updated type"
}

###
// Delete type by ID
DELETE http://localhost:5000/api/types/66bdf9590fb7e51ea15f2fad HTTP/1.1
